# Config file for automatic testing at travis-ci.org
sudo: required
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
dist: trusty
addons:
  chrome: stable

env:
  global:
    - CHROMEDRIVER=78.0.3904.70

before_install:
  - wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER/chromedriver_linux64.zip
  - mkdir $HOME/chromedriver && unzip /tmp/chromedriver.zip -d $HOME/chromedriver
  - export PATH=$HOME/chromedriver:$PATH
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U codecov
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
  - codecov
