# Config file for automatic testing at travis-ci.org
sudo: required
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
dist: trusty
addons:
  chrome: stable

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
  - codecov
